name: flutter_notifier_package
description: A new Flutter package.
version: 0.0.1+1

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  synchronized: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
